language: cpp

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
      compiler: gcc
      env: JOBS=4
    - os: osx
      compiler: clang
      env: CPPFLAGS=-I/usr/local/opt/openblas/include JOBS=2

addons:
  apt:
    packages:
      - libboost-all-dev
      - gfortran
      - automake
      - autoconf
      - autoconf-archive
      - autotools-dev
      - libblas-dev
      - liblapack-dev
      - libsdl2-dev
      - libompl-dev
      - coinor-libclp-dev
      - libglpk-dev
      - libav-tools
      - doxygen
      - groff

install:
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then
      ./install-apt.sh;
      if [ ! -e /usr/local/lib/libfcl.so ]; then
        wget -O - https://github.com/danfis/libccd/archive/v2.0.tar.gz | tar zxf - ;
        cd libccd-2.0;
        cmake .;
        make -j $JOBS && sudo make install;
        cd ..;
        wget -O - https://github.com/flexible-collision-library/fcl/archive/0.4.0.tar.gz | tar zxf - ;
        cd fcl-0.4.0;
        cmake .;
        make -j $JOBS && sudo make install;
        sudo ldconfig;
        cd ..;
      fi;
    fi;
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then
       brew update;
       brew tap homebrew/science;
       brew unlink libtool;
       brew install autoconf-archive openblas maxima sdl2 libtool ompl;
       brew install https://raw.github.com/dartsim/homebrew-dart/master/fcl.rb;
    fi

script:
  - autoreconf -i
  - ./configure --without-ompl --without-common-lisp;
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then
       make -k -j $JOBS distcheck;
    fi;
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then
       make -k -j $JOBS && make check;
    fi

cache:
  apt: true
  directories:
    - /usr/local


#before_install:
  #- sudo docker pull ubuntu:xenial
  #- docker ps -a
